# Generated by Django 5.2.1 on 2025-08-02 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('researcher', 'Researcher'), ('admin', 'Admin')], default='doctor', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('medical_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('pulmonologist', 'Pulmonologist'), ('radiologist', 'Radiologist'), ('general_practitioner', 'General Practitioner'), ('cardiothoracic_surgeon', 'Cardiothoracic Surgeon'), ('other', 'Other')], max_length=50, null=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_license_file', models.FileField(blank=True, null=True, upload_to='medical_licenses/')),
                ('research_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation_type', models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty'), ('postdoc', 'Postdoc'), ('researcher', 'Researcher'), ('other', 'Other')], max_length=50, null=True)),
                ('purpose_of_use', models.CharField(blank=True, choices=[('research', 'Research'), ('model_testing', 'Model Testing'), ('academic_study', 'Academic Study'), ('clinical_validation', 'Clinical Validation'), ('other', 'Other')], max_length=50, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('institutional_id_file', models.FileField(blank=True, null=True, upload_to='institutional_ids/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
