# Generated by Django 5.2.1 on 2025-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_account_status_user_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation_type',
            field=models.CharField(blank=True, choices=[('student', 'Student (Undergraduate/Graduate)'), ('phd_student', 'PhD Student'), ('postdoc', 'Postdoctoral Researcher'), ('faculty', 'Faculty Member'), ('research_scientist', 'Research Scientist'), ('principal_investigator', 'Principal Investigator'), ('industry_researcher', 'Industry Researcher'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='purpose_of_use',
            field=models.CharField(blank=True, choices=[('academic_research', 'Academic Research'), ('model_testing', 'Model Testing & Validation'), ('algorithm_development', 'Algorithm Development'), ('clinical_trial', 'Clinical Trial Research'), ('thesis_project', 'Thesis/Dissertation Project'), ('collaborative_study', 'Collaborative Study'), ('educational_purpose', 'Educational Purpose'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('pulmonologist', 'Pulmonologist'), ('radiologist', 'Radiologist'), ('internist', 'Internal Medicine'), ('emergency', 'Emergency Medicine'), ('family', 'Family Medicine'), ('thoracic_surgeon', 'Thoracic Surgeon'), ('respiratory_therapist', 'Respiratory Therapist'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
